name: team9_project
description: ----
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core packages
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.8
  country_code_picker: ^3.3.0
  badges: ^3.1.2
  pie_chart: ^5.4.0
  fl_chart: ^1.0.0

  intl_phone_field: ^3.2.0
  # intl_phone_number_input: ^0.7.3+1
  # flutter_multi_formatter: ^2.12.2
  uuid: ^4.0.0

  # ✅ Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase: ^9.0.0
  csv: ^6.0.0
  share_plus: ^11.0.0
  pdf: ^3.10.8
  printing: ^5.11.0
  firebase_storage: ^12.4.7
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
