// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuJsqwg_VsayW5VGteYl2oTa30Ryodm1k',
    appId: '1:1018056298137:web:3c698a7cbed420af437208',
    messagingSenderId: '1018056298137',
    projectId: 'finalprojectas-223b1',
    authDomain: 'finalprojectas-223b1.firebaseapp.com',
    storageBucket: 'finalprojectas-223b1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8-_2QJKjGRb3YH44h4ziHLwWb_AHrKf8',
    appId: '1:1018056298137:android:b09fa1066fcd6eb6437208',
    messagingSenderId: '1018056298137',
    projectId: 'finalprojectas-223b1',
    storageBucket: 'finalprojectas-223b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHXF9jrJFJFMZq2AFFgZmVxpi4gJK08Gg',
    appId: '1:1018056298137:ios:ba1c9ed99f567c01437208',
    messagingSenderId: '1018056298137',
    projectId: 'finalprojectas-223b1',
    storageBucket: 'finalprojectas-223b1.firebasestorage.app',
    iosBundleId: 'com.example.team9Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHXF9jrJFJFMZq2AFFgZmVxpi4gJK08Gg',
    appId: '1:1018056298137:ios:ba1c9ed99f567c01437208',
    messagingSenderId: '1018056298137',
    projectId: 'finalprojectas-223b1',
    storageBucket: 'finalprojectas-223b1.firebasestorage.app',
    iosBundleId: 'com.example.team9Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuJsqwg_VsayW5VGteYl2oTa30Ryodm1k',
    appId: '1:1018056298137:web:11229d7fe87c38d5437208',
    messagingSenderId: '1018056298137',
    projectId: 'finalprojectas-223b1',
    authDomain: 'finalprojectas-223b1.firebaseapp.com',
    storageBucket: 'finalprojectas-223b1.firebasestorage.app',
  );
}
